"""New migration

Revision ID: 6b279d6f1476
Revises: 5125424024bb
Create Date: 2024-08-01 12:16:09.510271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b279d6f1476'
down_revision: Union[str, None] = '5125424024bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_space', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domain_type', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_space', schema=None) as batch_op:
        batch_op.drop_column('domain_type')

    # ### end Alembic commands ###
